# Generated by Django 5.2 on 2025-07-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='status',
            field=models.CharField(choices=[('INIT', 'Забег инициализирован'), ('IN_PROGRESS', 'Забег начат'), ('FINISHED', 'Забег закончен')], default='INIT'),
        ),
    ]
