# Generated by Django 5.2 on 2025-07-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0004_athleteinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='athleteinfo',
            old_name='user_id',
            new_name='athlete',
        ),
        migrations.AlterField(
            model_name='athleteinfo',
            name='goals',
            field=models.TextField(default=''),
        ),
    ]
