# Generated by Django 5.2 on 2025-07-15 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0005_challenge'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Challenge',
        ),
    ]
