# Generated by Django 5.2 on 2025-07-15 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0006_delete_challenge'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AthleteInfo',
        ),
    ]
