# Generated by Django 5.2 on 2025-07-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0007_remove_athleteinfo_id_alter_athleteinfo_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athleteinfo',
            name='user_id',
        ),
        migrations.AddField(
            model_name='athleteinfo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
