# Generated by Django 5.2 on 2025-07-17 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0009_challenge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, serialize=False, to='app_run.run')),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=6)),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=7)),
            ],
        ),
    ]
