# Generated by Django 5.2 on 2025-07-17 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0010_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='position',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_run.run'),
        ),
    ]
