# Generated by Django 5.2 on 2025-07-17 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0010_position'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Position',
        ),
    ]
